//! Service detail panel with action buttons.

use gtk4::prelude::*;
use gtk4::{self as gtk, Align, Image, Label, Orientation};
use libadwaita as adw;
use libadwaita::prelude::*;
use std::cell::{Cell, RefCell};
use std::rc::Rc;

use crate::models::{ServiceAction, StateTone, UnitDetail};
use crate::utils::format_bytes;

type EnableHandlers = Rc<RefCell<Vec<Box<dyn Fn(bool)>>>>;

const TONE_CLASSES: &[&str] = &["success", "warning", "error", "dimmed"];

/// Whether the unit-file state counts as enabled for the toggle switch.
fn unit_is_enabled(state: &str) -> bool {
    matches!(state, "enabled" | "enabled-runtime")
}

/// Whether enable/disable can be toggled for this unit-file state.
fn unit_enable_can_toggle(state: &str) -> bool {
    matches!(state, "enabled" | "enabled-runtime" | "disabled")
}

fn tone_css_class(tone: StateTone) -> Option<&'static str> {
    match tone {
        StateTone::Success => Some("success"),
        StateTone::Warning => Some("warning"),
        StateTone::Error => Some("error"),
        StateTone::Muted => Some("dimmed"),
        StateTone::Normal => None,
    }
}

fn apply_tone(widget: &impl WidgetExt, tone: StateTone) {
    for class in TONE_CLASSES {
        widget.remove_css_class(class);
    }
    if let Some(class) = tone_css_class(tone) {
        widget.add_css_class(class);
    }
}

fn active_state_icon(active_state: &str) -> &'static str {
    match active_state {
        "active" => "emblem-ok-symbolic",
        "inactive" => "window-close-symbolic",
        "failed" => "dialog-error-symbolic",
        "activating" | "deactivating" | "reloading" => "content-loading-symbolic",
        _ => "dialog-question-symbolic",
    }
}

fn active_state_tone(active_state: &str) -> StateTone {
    match active_state {
        "active" => StateTone::Success,
        "failed" => StateTone::Error,
        "activating" | "deactivating" | "reloading" => StateTone::Warning,
        "inactive" => StateTone::Muted,
        _ => StateTone::Normal,
    }
}

/// Friendly subtitle for the Enabled switch.
fn enabled_subtitle(state: &str) -> String {
    match state {
        "enabled" => "Starts automatically at boot".into(),
        "enabled-runtime" => "Enabled until next reboot".into(),
        "disabled" => "Does not start at boot".into(),
        "static" => "Always available (static unit)".into(),
        "masked" | "masked-runtime" => "Masked — cannot be started".into(),
        "indirect" => "Enabled indirectly by another unit".into(),
        "generated" => "Generated by the system".into(),
        "transient" => "Temporary unit".into(),
        "alias" => "Alias of another unit".into(),
        "" => "—".into(),
        other => other.to_string(),
    }
}

fn action_tooltip(action: ServiceAction, running: bool, sensitive: bool) -> String {
    if sensitive {
        return action.tooltip().into();
    }
    match action {
        ServiceAction::Start if running => "Service is already running".into(),
        ServiceAction::Stop | ServiceAction::Restart | ServiceAction::Reload if !running => {
            "Service is not running".into()
        }
        _ => action.tooltip().into(),
    }
}

pub struct ServiceDetailPage {
    pub widget: gtk::Box,
    title: Label,
    description: Label,
    status_icon: Image,
    status_label: Label,
    active_state: Label,
    sub_state: Label,
    main_pid: Label,
    memory: Label,
    exec_start: Label,
    fragment_path: Label,
    enabled_row: adw::SwitchRow,
    action_box: gtk::FlowBox,
    stack: gtk::Stack,
    enable_handlers: EnableHandlers,
    updating_enabled: Rc<Cell<bool>>,
}

impl ServiceDetailPage {
    pub fn new() -> Self {
        let outer = gtk::Box::new(Orientation::Vertical, 0);
        outer.set_hexpand(true);

        let stack = gtk::Stack::new();
        stack.set_hexpand(true);
        stack.set_vexpand(true);

        let empty = adw::StatusPage::builder()
            .icon_name("application-x-executable-symbolic")
            .title("No service selected")
            .description("Select a service from the list to view its details.")
            .build();

        let content = gtk::Box::new(Orientation::Vertical, 12);
        content.set_margin_top(12);
        content.set_margin_bottom(8);
        content.set_margin_start(12);
        content.set_margin_end(12);

        let title = Label::builder()
            .label("—")
            .css_classes(["title-2"])
            .halign(Align::Start)
            .selectable(true)
            .ellipsize(gtk::pango::EllipsizeMode::End)
            .build();
        content.append(&title);

        let description = Label::builder()
            .label("")
            .css_classes(["dimmed"])
            .halign(Align::Start)
            .wrap(true)
            .xalign(0.0)
            .selectable(true)
            .build();
        content.append(&description);

        // Compact status chip under the description.
        let status_icon = Image::builder()
            .icon_name("dialog-question-symbolic")
            .pixel_size(16)
            .valign(Align::Center)
            .build();
        let status_label = Label::builder()
            .label("—")
            .halign(Align::Start)
            .xalign(0.0)
            .css_classes(["caption-heading"])
            .ellipsize(gtk::pango::EllipsizeMode::End)
            .build();
        let status_row = gtk::Box::new(Orientation::Horizontal, 8);
        status_row.set_halign(Align::Start);
        status_row.add_css_class("card");
        status_row.set_margin_top(2);
        status_row.set_margin_bottom(2);
        let status_inner = gtk::Box::new(Orientation::Horizontal, 8);
        status_inner.set_margin_start(10);
        status_inner.set_margin_end(10);
        status_inner.set_margin_top(6);
        status_inner.set_margin_bottom(6);
        status_inner.append(&status_icon);
        status_inner.append(&status_label);
        status_row.append(&status_inner);
        content.append(&status_row);

        // Lifecycle actions with icons; FlowBox wraps in a narrow inspector.
        let actions_heading = Label::builder()
            .label("Actions")
            .css_classes(["heading"])
            .halign(Align::Start)
            .margin_top(4)
            .build();
        content.append(&actions_heading);

        let actions_hint = Label::builder()
            .label("Start, stop, restart, or reload this service")
            .css_classes(["dimmed", "caption"])
            .halign(Align::Start)
            .wrap(true)
            .xalign(0.0)
            .build();
        content.append(&actions_hint);

        let action_box = gtk::FlowBox::builder()
            .selection_mode(gtk::SelectionMode::None)
            .homogeneous(true)
            .column_spacing(8)
            .row_spacing(8)
            .max_children_per_line(4)
            .min_children_per_line(2)
            .halign(Align::Fill)
            .hexpand(true)
            .build();
        action_box.set_margin_top(2);

        for action in [
            ServiceAction::Start,
            ServiceAction::Stop,
            ServiceAction::Restart,
            ServiceAction::Reload,
        ] {
            let content_widget = adw::ButtonContent::builder()
                .icon_name(action.icon_name())
                .label(action.label())
                .can_shrink(true)
                .build();

            let btn = gtk::Button::builder()
                .child(&content_widget)
                .tooltip_text(action.tooltip())
                .hexpand(true)
                .build();
            btn.add_css_class("pill");
            match action {
                ServiceAction::Start => btn.add_css_class("suggested-action"),
                ServiceAction::Stop => btn.add_css_class("destructive-action"),
                _ => {}
            }
            btn.set_action_name(Some("win.service-action"));
            btn.set_action_target_value(Some(&action.as_str().to_variant()));

            // FlowBox expects flow children; append the button directly.
            action_box.insert(&btn, -1);
        }
        content.append(&action_box);

        let group = adw::PreferencesGroup::new();
        group.set_title("Details");
        group.set_description(Some("Runtime state and unit file information"));

        let active_state = Self::value_label();
        let sub_state = Self::value_label();
        let main_pid = Self::value_label();
        let memory = Self::value_label();
        let exec_start = Self::value_label();
        let fragment_path = Self::value_label();

        let enabled_row = adw::SwitchRow::builder()
            .title("Enabled")
            .subtitle("—")
            .active(false)
            .sensitive(false)
            .build();
        enabled_row.set_tooltip_text(Some(
            "When on, the service is enabled to start automatically at boot",
        ));

        group.add(&Self::row("Active State", &active_state));
        group.add(&Self::row("Sub State", &sub_state));
        group.add(&Self::row("Main PID", &main_pid));
        group.add(&Self::row("Memory", &memory));
        group.add(&enabled_row);
        group.add(&Self::row("ExecStart", &exec_start));
        group.add(&Self::row("Unit File", &fragment_path));

        content.append(&group);

        let scrolled = gtk::ScrolledWindow::builder()
            .child(&content)
            .hscrollbar_policy(gtk::PolicyType::Never)
            .vexpand(true)
            .build();

        stack.add_named(&empty, Some("empty"));
        stack.add_named(&scrolled, Some("detail"));
        stack.set_visible_child_name("empty");

        outer.append(&stack);

        let enable_handlers: EnableHandlers = Rc::new(RefCell::new(Vec::new()));
        let updating_enabled = Rc::new(Cell::new(false));

        {
            let handlers = enable_handlers.clone();
            let updating = updating_enabled.clone();
            enabled_row.connect_active_notify(move |row| {
                if updating.get() {
                    return;
                }
                let active = row.is_active();
                for handler in handlers.borrow().iter() {
                    handler(active);
                }
            });
        }

        Self {
            widget: outer,
            title,
            description,
            status_icon,
            status_label,
            active_state,
            sub_state,
            main_pid,
            memory,
            exec_start,
            fragment_path,
            enabled_row,
            action_box,
            stack,
            enable_handlers,
            updating_enabled,
        }
    }

    fn value_label() -> Label {
        Label::builder()
            .label("—")
            .xalign(1.0)
            .hexpand(true)
            .selectable(true)
            .wrap(true)
            .max_width_chars(40)
            .build()
    }

    fn row(title: &str, value: &Label) -> adw::ActionRow {
        let row = adw::ActionRow::builder().title(title).build();
        row.add_suffix(value);
        row.set_activatable(false);
        row
    }

    pub fn clear(&self) {
        self.stack.set_visible_child_name("empty");
        self.set_enabled_switch(false, false, "—");
        self.set_status_chip("—", "dialog-question-symbolic", StateTone::Normal);
        self.set_actions_enabled(false);
    }

    pub fn set_detail(&self, detail: &UnitDetail) {
        self.stack.set_visible_child_name("detail");
        self.title.set_label(&detail.name);
        self.description.set_label(&detail.description);
        self.active_state.set_label(&detail.active_state);
        self.sub_state.set_label(&detail.sub_state);
        self.main_pid.set_label(&if detail.main_pid == 0 {
            "—".into()
        } else {
            detail.main_pid.to_string()
        });
        self.memory.set_label(&match detail.memory_bytes {
            Some(b) => format_bytes(b),
            None => "—".into(),
        });
        self.exec_start.set_label(if detail.exec_start.is_empty() {
            "—"
        } else {
            &detail.exec_start
        });
        self.fragment_path
            .set_label(if detail.fragment_path.is_empty() {
                "—"
            } else {
                &detail.fragment_path
            });

        let tone = active_state_tone(&detail.active_state);
        let status_text = format!("{} · {}", detail.active_state, detail.sub_state);
        self.set_status_chip(
            &status_text,
            active_state_icon(&detail.active_state),
            tone,
        );

        let state = detail.enabled_state.as_str();
        self.set_enabled_switch(
            unit_is_enabled(state),
            unit_enable_can_toggle(state),
            &enabled_subtitle(state),
        );

        // Lifecycle action sensitivity + contextual tooltips.
        let running = detail.active_state == "active";
        self.update_action_buttons(running);
    }

    pub fn set_loading_name(&self, name: &str) {
        self.stack.set_visible_child_name("detail");
        self.title.set_label(name);
        self.description.set_label("Loading…");
        self.set_status_chip(
            "Loading…",
            "content-loading-symbolic",
            StateTone::Warning,
        );
        self.set_enabled_switch(false, false, "Loading…");
        self.set_actions_enabled(false);
    }

    /// Subscribe to user toggles of the Enabled switch.
    ///
    /// `true` means the user wants the unit enabled; `false` means disabled.
    /// Programmatic updates from `set_detail` do not fire this callback.
    pub fn connect_enable_toggled<F: Fn(bool) + 'static>(&self, f: F) {
        self.enable_handlers.borrow_mut().push(Box::new(f));
    }

    fn set_status_chip(&self, text: &str, icon: &str, tone: StateTone) {
        self.status_label.set_label(text);
        self.status_icon.set_icon_name(Some(icon));
        apply_tone(&self.status_icon, tone);
        apply_tone(&self.status_label, tone);
    }

    fn set_enabled_switch(&self, active: bool, sensitive: bool, subtitle: &str) {
        self.updating_enabled.set(true);
        self.enabled_row.set_subtitle(subtitle);
        if self.enabled_row.is_active() != active {
            self.enabled_row.set_active(active);
        }
        self.enabled_row.set_sensitive(sensitive);
        self.updating_enabled.set(false);
    }

    fn set_actions_enabled(&self, enabled: bool) {
        let mut i = 0;
        while let Some(child) = self.action_box.child_at_index(i) {
            if let Some(btn) = child.child().and_then(|w| w.downcast::<gtk::Button>().ok()) {
                btn.set_sensitive(enabled);
            }
            i += 1;
        }
    }

    fn update_action_buttons(&self, running: bool) {
        let mut i = 0;
        while let Some(child) = self.action_box.child_at_index(i) {
            if let Some(btn) = child.child().and_then(|w| w.downcast::<gtk::Button>().ok()) {
                if let Some(target) = btn.action_target_value() {
                    let action_str = target.str().unwrap_or_default();
                    let action = match action_str {
                        "start" => Some(ServiceAction::Start),
                        "stop" => Some(ServiceAction::Stop),
                        "restart" => Some(ServiceAction::Restart),
                        "reload" => Some(ServiceAction::Reload),
                        _ => None,
                    };
                    if let Some(action) = action {
                        let sensitive = match action {
                            ServiceAction::Start => !running,
                            ServiceAction::Stop
                            | ServiceAction::Restart
                            | ServiceAction::Reload => running,
                            _ => true,
                        };
                        btn.set_sensitive(sensitive);
                        btn.set_tooltip_text(Some(&action_tooltip(action, running, sensitive)));
                    }
                }
            }
            i += 1;
        }
    }
}

impl Default for ServiceDetailPage {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::{enabled_subtitle, unit_enable_can_toggle, unit_is_enabled};
    use crate::models::ServiceAction;

    #[test]
    fn enabled_states_map_to_switch() {
        assert!(unit_is_enabled("enabled"));
        assert!(unit_is_enabled("enabled-runtime"));
        assert!(!unit_is_enabled("disabled"));
        assert!(!unit_is_enabled("static"));
        assert!(!unit_is_enabled("masked"));
    }

    #[test]
    fn only_enabled_or_disabled_can_toggle() {
        assert!(unit_enable_can_toggle("enabled"));
        assert!(unit_enable_can_toggle("enabled-runtime"));
        assert!(unit_enable_can_toggle("disabled"));
        assert!(!unit_enable_can_toggle("static"));
        assert!(!unit_enable_can_toggle("masked"));
        assert!(!unit_enable_can_toggle("indirect"));
        assert!(!unit_enable_can_toggle("generated"));
    }

    #[test]
    fn enabled_subtitles_are_human_readable() {
        assert!(enabled_subtitle("enabled").contains("boot"));
        assert!(enabled_subtitle("disabled").contains("Does not"));
        assert!(enabled_subtitle("masked").contains("Masked"));
    }

    #[test]
    fn lifecycle_actions_have_icons_and_tooltips() {
        for action in [
            ServiceAction::Start,
            ServiceAction::Stop,
            ServiceAction::Restart,
            ServiceAction::Reload,
        ] {
            assert!(action.icon_name().ends_with("-symbolic"));
            assert!(!action.tooltip().is_empty());
        }
    }
}
